language: go

go:
  - 1.9

# only run build on master and tag
branches:
  only:
  - master

env:
  - APP=$TRAVIS_OS_NAME.exe

os:
  - linux

install:
  - cd project/go
  - export GOPATH=$GOPATH:`pwd`
  - go get -d ./src/*
  - pwd
  - ls -a ./src
  - export FINAL=`pwd`/dist/xmain
  - go build -o dist/xmain -ldflags="-s -w" src/xmain/*.go
  - ls -alh dist
  - ls -alh $FINAL

before_deploy:
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then zip $FINAL.zip $FINAL    ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then /c/Program\ Files/7-Zip/7z.exe a $APP.zip ${APP}.exe    ; fi


deploy:
  provider: releases
  api_key: $GH_TOKEN  # set in travis website
  file: $FINAL.zip
  file: $FINAL
  skip_cleanup: true
  on:
    tags: false      # only deploy tag commit

