language: go

go:
  - 1.9

# only run build on master and tag
branches:
  only:
  - master

os:
  - linux

install:
  - cd project/go
  - export TRAVIS_TAG=latest
  - export GOPATH=$GOPATH:`pwd`
  - rm -rf src/github.com; 
  - GOOS=darwin GOARCH=amd64 go get -d ./src/*
  - GOOS=darwin GOARCH=amd64 go build -o dist/x-installer.mac-x64 -ldflags="-s -w" src/xmain/*.go
  - rm -rf src/github.com; 
  - GOOS=linux GOARCH=amd64 go get -d ./src/*
  - GOOS=linux GOARCH=amd64 go build -o dist/x-installer.linux-x64 -ldflags="-s -w" src/xmain/*.go
  - rm -rf src/github.com; 
  - GOOS=linux GOARCH=arm go get -d ./src/*
  - GOOS=linux GOARCH=arm go build -o dist/x-installer.linux-arm -ldflags="-s -w" src/xmain/*.go
  - rm -rf src/github.com; 
  - GOOS=windows GOARCH=amd64 go get -d ./src/*
  - GOOS=windows GOARCH=amd64 go build -o dist/x-installer.windows.exe -ldflags="-s -w" src/xmain/*.go

deploy:
  provider: releases
  api_key: $GH_TOKEN  # set in travis website
  file: 
    - dist/x-installer.mac-x64
    - dist/x-installer.linux-x64
    - dist/x-installer.linux-arm
    - dist/x-installer.windows.exe

  skip_cleanup: true
  on:
    tags: false      # only deploy tag commit

