language: go

go:
  - 1.9

# only run build on master and tag
branches:
  only:
  - master

env:
  - APP=$TRAVIS_OS_NAME.exe

os:
  - linux

install:
  - cd project/go
  - export GOPATH=$GOPATH:`pwd`
  - go get -d ./src/*
  - pwd
  - ls -a ./src
  - export FINAL=`pwd`/dist/xmain
  - ls -alh $FINAL
  - go build -o dist/xmain -ldflags="-s -w" src/xmain/*.go

deploy:
  provider: releases
  api_key: $GH_TOKEN  # set in travis website
  file: $FINAL
  skip_cleanup: false
  on:
    tags: false      # only deploy tag commit

