language: go

go:
  - "1.12"

# only run build on master and tag
branches:
  only:
  - master

os:
  - linux

install:
  - echo "ignore"

script:
  - TRAVIS_TAG=latest-dev
  - sudo apt update && sudo apt install upx -y
  - cd project/go
  - GOPATH=`pwd`
  - bash dev.sh dist.all

deploy:
  provider: releases
  api_key: $GH_TOKEN  # set in travis website
  file_glob: true
  file: dist/*
  overwrite: true
  skip_cleanup: true
  on:
    tags: true      # only deploy tag commit

