language: go

go:
  - 1.9

# only run build on master and tag
branches:
  only:
  - master

env:
  - APP=$TRAVIS_OS_NAME.exe

os:
  - linux

install:
  - cd project/go
  - GOPATH="`pwd`" go get -d ./src/*
  - GOPATH="`pwd`" go build -o dist/xmain -ldflags="-s -w" src/xmain/*.go

deploy:
  provider: releases
  api_key: $GH_TOKEN  # set in travis website
  file: project/go/dist/xmain
  skip_cleanup: false
  on:
    tags: true      # only deploy tag commit

